### ISSUE TITLE
[racket-language-server] Is this repo still useful? Can it be safely archived? 

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/racket-language-server#20]
Hi @dvc94ch.

I am an admin on the `theia-ide` GitHub organization. Most of the repos here have moved to Eclipse Foundation organizations. I am doing a cleanup pass. Can you confirm if this repo is still useful and should be kept? Else I would archive it.

Please let me know.

**Comment by dvc94ch** [comment]
I guess if you want a racket language server there isn't much else. But I've moved on to other projects.

**Comment by marcdumais-work** [comment]
Thanks for the quick answer. Since I understand that this repo is no longer actively maintained, I will archive it. It will still be available in read-only mode. We can un-archive it, if the situation changes.
